### ISSUE TITLE
Not returning results

### ISSUE THREAD

**Issue by Hightower1** [panayiotisp/DotCyToolboxPlugins#4]
I love the concept of this tool but when i click on compare selected roles i'm not getting anything to show.  Any ideas would be appreciated. 

 
![image](https://user-images.githubusercontent.com/37645475/46168060-049dd600-c25d-11e8-987e-1d21f06decb4.png)

**Comment by panayiotisp** [comment]
Let me check

**Comment by Hightower1** [comment]
The issue was with me. I was looking at the wrong Business Unit. All is good.
